import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("data.csv")
print(data)
print(data.head(3))
print(data.shape)
print(data.columns.tolist())
print(data["score"])
print("How many people:", len(data))
print("Average score:",data["score"].mean())
print("Highest score:",data["score"].max())
print("Lowest score:",data["score"].min())
top= data["score"].idxmax()
print("Top scorer:", data.loc[top])
high=data[data["score"]>80]
print(high)
print("How many scored above 80:", len(high))
print(data.groupby("city")["score"].mean())
plt.bar(data["name"], data["score"])
plt.title("Score by person")
plt.xlabel("Name")
plt.ylabel("Score")
plt.savefig("chart.png")
plt.show()
data = pd.read_csv(r"C:\Users\USER\Desktop\detective\messy.csv")
print(data.isnull().sum())
